/*
 * generated by Xtext 2.19.0
 */
package ml.classification.tests

import com.google.inject.Inject

import ml.classification.dSL.ML
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import java.nio.file.Files
import java.nio.file.Paths
import ml.classification.generator.PrettyPrinter

@ExtendWith(InjectionExtension)
@InjectWith(DSLInjectorProvider)
class DSLPrettyPrinterTest {
	@Inject
	ParseHelper<ML> parseHelper
	//"C:/Utilisateurs/Utilisateur/Documents/ESIR/ESIR3-SIF/DSL/ProjetGit/Tests/prettyprinter/input/1.mldsl"
	
	def boolean equals(CharSequence a, CharSequence b){
		if (a.length!=b.length){
			return false
		}
		for ( var i = 0; i < a.length ; i++){
			if (a.charAt(i)!=b.charAt(i)) {
				return false
			}
		}
		return true
	}
	
	@Test
	def void testPrettyPrinterOutput() {
		val prettyPrinter = new PrettyPrinter
		val input = parseHelper.parse(Files.readString(Paths.get("../../DSL-Project/ml.classification.dsl.tests/TestFiles/prettyprinter/input/1.mldsl")))
		Assertions.assertNotNull(input)
		val output = prettyPrinter.prettyprint(input)
		Assertions.assertNotNull(output)
		print(output)
		val expected_output = Files.readString(Paths.get("../../DSL-Project/ml.classification.dsl.tests/TestFiles/prettyprinter/expected/1.mldsl"))
		print("\n"+expected_output)
		Assertions.assertTrue(equals(output,expected_output))
	}
}
