/**
 * generated by Xtext 2.23.0
 */
package ml.classification.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algo choose</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ml.classification.dSL.Algo_choose#getAlgorithm <em>Algorithm</em>}</li>
 * </ul>
 *
 * @see ml.classification.dSL.DSLPackage#getAlgo_choose()
 * @model
 * @generated
 */
public interface Algo_choose extends EObject
{
  /**
   * Returns the value of the '<em><b>Algorithm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithm</em>' attribute.
   * @see #setAlgorithm(String)
   * @see ml.classification.dSL.DSLPackage#getAlgo_choose_Algorithm()
   * @model
   * @generated
   */
  String getAlgorithm();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Algo_choose#getAlgorithm <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithm</em>' attribute.
   * @see #getAlgorithm()
   * @generated
   */
  void setAlgorithm(String value);

} // Algo_choose
