/**
 * generated by Xtext 2.23.0
 */
package ml.classification.dSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ML</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ml.classification.dSL.ML#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see ml.classification.dSL.DSLPackage#getML()
 * @model
 * @generated
 */
public interface ML extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link ml.classification.dSL.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see ml.classification.dSL.DSLPackage#getML_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // ML
