/**
 * generated by Xtext 2.23.0
 */
package ml.classification.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ml.classification.dSL.Primitive#getPrint <em>Print</em>}</li>
 *   <li>{@link ml.classification.dSL.Primitive#getAlgo_choose <em>Algo choose</em>}</li>
 *   <li>{@link ml.classification.dSL.Primitive#getRead <em>Read</em>}</li>
 *   <li>{@link ml.classification.dSL.Primitive#getStrategy_choose <em>Strategy choose</em>}</li>
 *   <li>{@link ml.classification.dSL.Primitive#getColumn <em>Column</em>}</li>
 *   <li>{@link ml.classification.dSL.Primitive#getUse_metric <em>Use metric</em>}</li>
 *   <li>{@link ml.classification.dSL.Primitive#getPredict <em>Predict</em>}</li>
 * </ul>
 *
 * @see ml.classification.dSL.DSLPackage#getPrimitive()
 * @model
 * @generated
 */
public interface Primitive extends EObject
{
  /**
   * Returns the value of the '<em><b>Print</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Print</em>' containment reference.
   * @see #setPrint(Print)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Print()
   * @model containment="true"
   * @generated
   */
  Print getPrint();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getPrint <em>Print</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Print</em>' containment reference.
   * @see #getPrint()
   * @generated
   */
  void setPrint(Print value);

  /**
   * Returns the value of the '<em><b>Algo choose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algo choose</em>' containment reference.
   * @see #setAlgo_choose(Algo_choose)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Algo_choose()
   * @model containment="true"
   * @generated
   */
  Algo_choose getAlgo_choose();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getAlgo_choose <em>Algo choose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algo choose</em>' containment reference.
   * @see #getAlgo_choose()
   * @generated
   */
  void setAlgo_choose(Algo_choose value);

  /**
   * Returns the value of the '<em><b>Read</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read</em>' containment reference.
   * @see #setRead(Read)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Read()
   * @model containment="true"
   * @generated
   */
  Read getRead();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getRead <em>Read</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read</em>' containment reference.
   * @see #getRead()
   * @generated
   */
  void setRead(Read value);

  /**
   * Returns the value of the '<em><b>Strategy choose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategy choose</em>' containment reference.
   * @see #setStrategy_choose(Strategy_choose)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Strategy_choose()
   * @model containment="true"
   * @generated
   */
  Strategy_choose getStrategy_choose();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getStrategy_choose <em>Strategy choose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strategy choose</em>' containment reference.
   * @see #getStrategy_choose()
   * @generated
   */
  void setStrategy_choose(Strategy_choose value);

  /**
   * Returns the value of the '<em><b>Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' containment reference.
   * @see #setColumn(Column)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Column()
   * @model containment="true"
   * @generated
   */
  Column getColumn();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getColumn <em>Column</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' containment reference.
   * @see #getColumn()
   * @generated
   */
  void setColumn(Column value);

  /**
   * Returns the value of the '<em><b>Use metric</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use metric</em>' containment reference.
   * @see #setUse_metric(Use_Metric)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Use_metric()
   * @model containment="true"
   * @generated
   */
  Use_Metric getUse_metric();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getUse_metric <em>Use metric</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use metric</em>' containment reference.
   * @see #getUse_metric()
   * @generated
   */
  void setUse_metric(Use_Metric value);

  /**
   * Returns the value of the '<em><b>Predict</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predict</em>' attribute.
   * @see #setPredict(String)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Predict()
   * @model
   * @generated
   */
  String getPredict();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getPredict <em>Predict</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predict</em>' attribute.
   * @see #getPredict()
   * @generated
   */
  void setPredict(String value);

} // Primitive
