/**
 * generated by Xtext 2.23.0
 */
package ml.classification.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ml.classification.dSL.Primitive#getPrimitive <em>Primitive</em>}</li>
 * </ul>
 *
 * @see ml.classification.dSL.DSLPackage#getPrimitive()
 * @model
 * @generated
 */
public interface Primitive extends EObject
{
  /**
   * Returns the value of the '<em><b>Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primitive</em>' containment reference.
   * @see #setPrimitive(EObject)
   * @see ml.classification.dSL.DSLPackage#getPrimitive_Primitive()
   * @model containment="true"
   * @generated
   */
  EObject getPrimitive();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Primitive#getPrimitive <em>Primitive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primitive</em>' containment reference.
   * @see #getPrimitive()
   * @generated
   */
  void setPrimitive(EObject value);

} // Primitive
