/**
 * generated by Xtext 2.23.0
 */
package ml.classification.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ml.classification.dSL.Print#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see ml.classification.dSL.DSLPackage#getPrint()
 * @model
 * @generated
 */
public interface Print extends EObject
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(Constant)
   * @see ml.classification.dSL.DSLPackage#getPrint_Val()
   * @model containment="true"
   * @generated
   */
  Constant getVal();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Print#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(Constant value);

} // Print
