/**
 * generated by Xtext 2.23.0
 */
package ml.classification.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Metric</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ml.classification.dSL.Use_Metric#getMetric <em>Metric</em>}</li>
 * </ul>
 *
 * @see ml.classification.dSL.DSLPackage#getUse_Metric()
 * @model
 * @generated
 */
public interface Use_Metric extends EObject
{
  /**
   * Returns the value of the '<em><b>Metric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metric</em>' attribute.
   * @see #setMetric(String)
   * @see ml.classification.dSL.DSLPackage#getUse_Metric_Metric()
   * @model
   * @generated
   */
  String getMetric();

  /**
   * Sets the value of the '{@link ml.classification.dSL.Use_Metric#getMetric <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metric</em>' attribute.
   * @see #getMetric()
   * @generated
   */
  void setMetric(String value);

} // Use_Metric
